language: generic

sudo: required
services:
 - docker
before_install:
 - docker build -t danielitzhak/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true danielitzhak/docker-react npm run test
